//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeerCalculator.DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BeerCalculatorEntities : DbContext
    {
        public BeerCalculatorEntities()
            : base("name=BeerCalculatorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Grain> Grains { get; set; }
        public virtual DbSet<GrainType> GrainTypes { get; set; }
        public virtual DbSet<Hop> Hops { get; set; }
        public virtual DbSet<HopType> HopTypes { get; set; }
        public virtual DbSet<Recipe> Recipes { get; set; }
        public virtual DbSet<Yeast> Yeasts { get; set; }
        public virtual DbSet<YeastType> YeastTypes { get; set; }
    }
}
