//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeerCalculator.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrainType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GrainType()
        {
            this.Grains = new HashSet<Grain>();
        }
    
        public int GrainTypeID { get; set; }
        public string GrainName { get; set; }
        public int MaximumSugarExtraction { get; set; }
        public int MaximumExtractionRate { get; set; }
        public decimal Lovibond { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Grain> Grains { get; set; }
    }
}
