//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeerCalculator.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hop
    {
        public int HopID { get; set; }
        public int HopTypeID { get; set; }
        public decimal Amount { get; set; }
        public decimal AlphaAcid { get; set; }
        public int RecipeID { get; set; }
        public int BoilTime { get; set; }
    
        public virtual HopType HopType { get; set; }
        public virtual Recipe Recipe { get; set; }
    }
}
