//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeerCalculator.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recipe()
        {
            this.Grains = new HashSet<Grain>();
            this.Hops = new HashSet<Hop>();
            this.Yeasts = new HashSet<Yeast>();
        }
    
        public int RecipeID { get; set; }
        public string RecipeName { get; set; }
        public decimal ExpectedABV { get; set; }
        public Nullable<decimal> ActualABV { get; set; }
        public decimal ExpectedOriginalGravity { get; set; }
        public Nullable<decimal> ActualOriginalGravity { get; set; }
        public decimal ExpectedFinalGravity { get; set; }
        public Nullable<decimal> ActualFinalGravity { get; set; }
        public int IBU { get; set; }
        public decimal BoilVolume { get; set; }
        public decimal FinalVolume { get; set; }
        public int ExpectedMashEfficiency { get; set; }
        public Nullable<int> ActualMashEfficiency { get; set; }
        public decimal BoilRate { get; set; }
        public decimal EquipmentDeadSpace { get; set; }
        public decimal GrainAbsorbtion { get; set; }
        public int MashTemperature { get; set; }
        public decimal MashThickness { get; set; }
        public decimal TrubLoss { get; set; }
        public decimal InitialGrainTemperature { get; set; }
        public int WaterRequired { get; set; }
        public decimal StrikeVolume { get; set; }
        public int StrikeTemperature { get; set; }
        public decimal SpargeVolume { get; set; }
        public int SpargeTemperature { get; set; }
        public decimal ExpectedBoilGravityPoints { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Grain> Grains { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hop> Hops { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yeast> Yeasts { get; set; }
    }
}
