//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrewProcess
    {
        public long BrewProcessID { get; set; }
        public Nullable<double> ActualABV { get; set; }
        public Nullable<double> ActualOG { get; set; }
        public Nullable<double> ActualFG { get; set; }
        public Nullable<int> ActualMashEfficiency { get; set; }
        public Nullable<int> RecipeID { get; set; }
        public Nullable<long> UserID { get; set; }
    
        public virtual Recipe Recipe { get; set; }
        public virtual User User { get; set; }
    }
}
