//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Grain
{
    public int GrainID { get; set; }
    public Nullable<int> GrainTypeID { get; set; }
    public Nullable<int> Amount { get; set; }
    public Nullable<long> BrewProcessID { get; set; }

    public virtual BrewProcess BrewProcess { get; set; }
    public virtual GrainType GrainType { get; set; }
}
