//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Hop
{
    public int HopID { get; set; }
    public Nullable<int> HopTypeID { get; set; }
    public int AlphaAcid { get; set; }
    public Nullable<long> BrewProcessID { get; set; }
    public double Amount { get; set; }

    public virtual BrewProcess BrewProcess { get; set; }
    public virtual HopType HopType { get; set; }
}
