//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recipe()
        {
            this.Grains = new HashSet<Grain>();
            this.Hops = new HashSet<Hop>();
            this.Yeasts = new HashSet<Yeast>();
        }
    
        public int RecipeID { get; set; }
        public string RecipeName { get; set; }
        public Nullable<double> ExpectedABV { get; set; }
        public Nullable<double> ActualABV { get; set; }
        public Nullable<double> ExpectedOG { get; set; }
        public Nullable<double> ActualOG { get; set; }
        public Nullable<double> ExpectedFG { get; set; }
        public Nullable<double> ActualFG { get; set; }
        public Nullable<int> IBU { get; set; }
        public Nullable<int> MashEfficiency { get; set; }
        public Nullable<System.DateTime> BrewDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Grain> Grains { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hop> Hops { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yeast> Yeasts { get; set; }
    }
}
