//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yeast
    {
        public int YeastID { get; set; }
        public Nullable<int> YeastTypeID { get; set; }
        public Nullable<long> BrewProcessID { get; set; }
    
        public virtual BrewProcess BrewProcess { get; set; }
        public virtual HopType HopType { get; set; }
    }
}
